ecourts/urls.py
from django.urls import path
from .import views

app_name='ecourts'

urlpatterns = [
	path('',views.index, name='index'),
	path('addstock/',views.addstock,name='addstock'),
	path('viewreceived/',views.viewreceived, name='viewreceived'),
	path('receiveddetail/<int:pk>',views.receiveddetail,name='receiveddetail'),
	path('issue',views.issue, name='issue'),
	path('editbulk/<int:pk>',views.editbulk, name='editbulk'),
	path('getstockajax/<int:pk>',views.getstockajax, name='getstockajax'),
	path('viewallissued/',views.viewallissued,name='viewallissued'),
	path('detailissued/<int:pk>',views.detailissued,name='detailissued'),
]

loginpage/urls.py
from django.urls import path
from .import views

app_name='loginpage'

urlpatterns = [
	# path('',views.index, name='index'),
	path('',views.loginuser,name='loginuser'),
	path('logout',views.logoutuser,name='logoutuser'),
	path('register',views.register,name='register'),
	path('changepassword',views.changepassword, name='changepassword'),
]

stockmanagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dashboard.urls')),
    path('loginpage/',include('loginpage.urls')),
    path('accounts/',include('accounts.urls')),
    path('ecourts/',include('ecourts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loginpage/models.py
from django.db import models

# Create your models here.

loginpage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, get_user_model, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from accounts.models import User,Section, Location

def index(request):
	if request.user.is_authenticated:
		return redirect("/dashboard")
	return render(request,'loginpage/index.html')

def loginuser(request):
	if request.method == 'POST':
		user=authenticate(username=request.POST['username'],password=request.POST['password'])
		if user is None:
			messages.warning(request, 'User not Present')
			return render(request,'loginpage/loginuser.html')
		if not user.is_staff:
			messages.warning(request, 'User not activated by admin')
			return render(request,'loginpage/loginuser.html')
		if user is not None:
			login(request, user)
			if request.GET.get('next'):
				return redirect(request.GET.get('next'))
			return redirect('/')
	return render(request,'loginpage/loginuser.html')

def logoutuser(request):
	logout(request)
	if request.GET.get('next'):
		return redirect(request.GET.get('next'))
	return redirect('/')

def register(request):
	if request.method == 'POST':
		if request.POST['password1'] != request.POST['password2']:
			messages.error(request,'Passwords dont match')
			return redirect('/loginpage/register')
		if User.objects.filter(username=request.POST['username']):
			messages.error(request,'UserName already present')
			return redirect('/loginpage/register')
		user = User.objects.create_user(username=request.POST['username'], 
			password=request.POST['password1'],)
		user.first_name = request.POST['first_name']
		user.last_name = request.POST['last_name']
		user.section = Section.objects.get(pk=request.POST['section'])
		user.location = Location.objects.get(pk=request.POST['location'])
		user.save()
		messages.info(request, 'User will get activated by admin')
		return redirect('/loginpage')
	context = {'sections':Section.objects.all(),'location':Location.objects.all()}
	return render(request,'loginpage/register.html',context)


def changepassword(request):
	if request.method == 'POST':
		if request.POST['password1'] != request.POST['password2']:
			messages.error(request,'Passwords dont match')
		user = User.objects.get(username__exact=request.POST['username'])
		user.set_password(request.POST['password1'])
		user.save()
		messages.success(request,'Password changed')
		return redirect('/loginpage/')
	return render(request,'loginpage/changepassword.html')

loginpage/templates/loginpage/baselogin.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title%}{% endblock %}</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container-fluid">
		<a class="navbar-brand" href="/">Home</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<!-- <li class="nav-item">
					<a class="nav-link active" aria-current="page" href="#">Home</a>
				</li> -->
			</ul>
			<a href="{% url 'loginpage:loginuser' %}" class="btn btn-outline-danger">Login</a>
		</div>
	</div>
</nav>
<body>
	{% block content %}
	{% endblock %}
</body>
</html>

loginpage/templates/loginpage/changepassword.html
{% extends 'loginpage/baselogin.html' %}
{% block title %} change password {% endblock %}
{% block content %}
<br><br>
{% if messages %}
	{% for message in messages %}
		<div class="alert alert-{{ message.tags }} alert-dismissible fade show container" role="alert">
			{{ message }}
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
	{% endfor %}
{% endif %}
<form method="post" class="container">
	{% csrf_token %}
	<input type="text" class="form-control" placeholder="username" name="username"><br>
	<input type="password" class="form-control" placeholder="password" name="password1"><br>
	<input type="password" class="form-control" placeholder="re enter password" name="password2"><br>
	<input type="submit" class="btn btn-outline-success">
</form>

{% endblock %}

loginpage/templates/loginpage/index.html
{% extends 'loginpage/baselogin.html' %}
{% block title%}Login{% endblock %}
{% block content %}

{% endblock %}

loginpage/templates/loginpage/loginuser.html
{% extends 'loginpage/baselogin.html' %}
{% block title%}Login{% endblock %}
{% block content %}
{% if messages %}
	{% for message in messages %}
		<div class="alert alert-{{ message.tags }} alert-dismissible fade show container text-center" role="alert">
			{{ message }}
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
	{% endfor %}
{% endif %}
<br>
<form class="container text-center" method="post">
	{% csrf_token %}
	<input type="text" name="username" class="form-control" placeholder="username">
	<br>
	<input type="password" name="password" class="form-control" placeholder="password">
	<br>
	<input type="submit" class="btn btn-outline-success btn-sm" value="submit">
	&nbsp
	<a href="{% url 'loginpage:register' %}" class="btn btn-outline-primary btn-sm">Register</a>&nbsp
	<a href="{% url 'loginpage:changepassword' %}" class="btn btn-outline-danger btn-sm">Change password</a>
</form>

{% endblock %}

loginpage/templates/loginpage/register.html
{% extends 'loginpage/baselogin.html' %}
{% block title%}Register{% endblock %}
{% block content %}
<br>

{% if messages %}
	{% for message in messages %}
		<div class="alert alert-danger alert-dismissible fade show container text-center" role="alert">
			{{ message }}
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
	{% endfor %}
{% endif %}

<form method="post" class="container" style="margin-top: 50px;">
	<table class="table text-center table-bordered">
		{% csrf_token %}
		<tr>
			<td><input type="text" class="form-control" name="first_name" placeholder="First Name" maxlength="100" autocomplete="off" required></td>
		</tr>
		<tr>
			<td><input type="text" class="form-control" name="last_name" placeholder="Last Name" maxlength="100" autocomplete="off" required></td>
		</tr>
		<tr>
			<td><input type="text" class="form-control" name="username" placeholder="username" maxlength="100" autocomplete="off" required></td>
		</tr>
			<td><input type="password" class="form-control" name="password1" placeholder="password1" required></td>
		</tr>
		<tr>
			<td><input type="password" class="form-control" name="password2" placeholder="Re enter password" required></td>
		</tr>
		<tr>
			<td>
				<select name="section" class="form-control">
					<option value="">-- section associated --</option>
					{% for section in sections %}
					<option value="{{ section.pk }}">{{ section.section_name }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
		<tr>
			<td>
				<select name="location" class="form-control">
					<option value="">- - select - -</option>
					{% for l in location %}
					<option value="{{ l.pk }}">{{ l }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
		<tr>
		<tr><td><input type="submit" class="btn btn-outline-success" value="submit"></td></tr>
	</table>
	</form>

{% endblock %}