ecourts/urls.py
from django.urls import path
from .import views

app_name='ecourts'

urlpatterns = [
	path('',views.index, name='index'),
	path('addstock/',views.addstock,name='addstock'),
	path('viewreceived/',views.viewreceived, name='viewreceived'),
	path('receiveddetail/<int:pk>',views.receiveddetail,name='receiveddetail'),
	path('issue',views.issue, name='issue'),
	path('editbulk/<int:pk>',views.editbulk, name='editbulk'),
	path('getstockajax/<int:pk>',views.getstockajax, name='getstockajax'),
	path('viewallissued/',views.viewallissued,name='viewallissued'),
	path('detailissued/<int:pk>',views.detailissued,name='detailissued'),
]

stockmanagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dashboard.urls')),
    path('loginpage/',include('loginpage.urls')),
    path('accounts/',include('accounts.urls')),
    path('ecourts/',include('ecourts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecourts/models.py
from django.db import models
from accounts.models import Section,User,Location


class BulkStock(models.Model):
	received_from = models.CharField(max_length=100)
	ref_no = models.CharField(max_length=50,null=True,blank=True)
	document = models.FileField(upload_to='ecourts/document/',null=True,blank=True)
	add_document = models.FileField(upload_to='ecourts/add_document/',null=True,blank=True)
	received_date = models.DateField()
	remarks = models.TextField(null=True,blank=True)
	entered_by = models.ForeignKey(User, on_delete=models.RESTRICT,null=True)
	location = models.ForeignKey(Location,on_delete=models.RESTRICT,null=True)

	def __str__(self):
		return self.received_from

class Item(models.Model):
	description = models.CharField(max_length=500)
	sl_no = models.CharField(max_length=100)
	specification = models.CharField(max_length=500)
	status = models.CharField(max_length=20)
	reason = models.CharField(max_length=200, null=True,blank=True)
	issued = models.BooleanField(default=False)
	stock_associated = models.ForeignKey(BulkStock, on_delete=models.RESTRICT,null=True)

	def __str__(self):
		return self.description

class Issue(models.Model):
	name = models.CharField(max_length=100)
	designation = models.CharField(max_length=100)
	date = models.DateField()
	remarks = models.TextField(null=True,blank=True)
	section = models.ForeignKey(Section,on_delete=models.RESTRICT,related_name='section')
	issued_by = models.ForeignKey(User, on_delete=models.RESTRICT,related_name='issued')
	requisition = models.FileField(upload_to='ecourts/requisition/',null=True,blank=True)
	current_status = models.CharField(max_length=100,null=True,blank=True)
	item = models.ForeignKey(Item, on_delete=models.RESTRICT,related_name='item', null=True)

	def __str__(self):
		return self.name

ecourts/forms.py
from django import forms
from .models import BulkStock,Item,Issue


class BulkStockForm(forms.ModelForm):
	class Meta:
		model = BulkStock
		fields = '__all__'

class ItemForm(forms.ModelForm):
	class Meta:
		model = Item
		fields = '__all__'

class IssueForm(forms.ModelForm):
	class Meta:
		model = Issue
		fields = '__all__'

ecourts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *
from accounts.models import Section, Location
from django.core.paginator import Paginator

def index(request):
	return render(request,'ecourts/index.html')

def savetostock(request,bulkmodel):
	descriptions = request.POST.getlist('description')
	sl_no = request.POST.getlist('sl_no')
	specification = request.POST.getlist('specification')
	status = request.POST.getlist('status')
	reason = request.POST.getlist('reason')
	for i in range(0,len(descriptions)):
		item = Item()
		item.description = descriptions[i]
		item.sl_no = sl_no[i]
		item.specification = specification[i]
		item.status = status[i]
		item.reason = reason[i]
		item.stock_associated = bulkmodel
		item.save()

def addstock(request):
	if request.method == 'POST':
		bulkform = BulkStockForm(request.POST,request.FILES)
		if bulkform.is_valid():
			bulkmodel = bulkform.save()
			savetostock(request,bulkmodel)
		else:
			print(bulkform.errors)
	return render(request,'ecourts/addstock.html',{'location':Location.objects.all()})

def viewreceived(request):
	bulks = BulkStock.objects.all()
	return render(request,'ecourts/received/viewreceived.html',{'bulks':bulks})

def receiveddetail(request,pk):
	bulk = BulkStock.objects.get(pk=pk)
	items = Item.objects.filter(stock_associated=bulk)
	return render(request,'ecourts/received/receiveddetail.html',{'bulk':bulk,'items':items})

def issue(request):
	if request.method == 'POST':
		print(request.FILES)
		# return redirect('/ecourts/issue')
		request.POST._mutable = True
		request.POST['issued_by'] = request.user
		request.POST['current_status'] = request.POST['name']
		issueform = IssueForm(request.POST,request.FILES)
		if issueform.is_valid():
			issueform.save()
			item = Item.objects.get(pk=request.POST['item'])
			item.issued = True
			item.save()
			return redirect('/ecourts/issue')
		else:
			return HttpResponse(issueform.errors)
	context = {
		'bulks':BulkStock.objects.all(),
		'sections':Section.objects.all(),
	}
	return render(request,'ecourts/issue/issue.html',context)

def editbulk(request,pk):
	bulkstock = BulkStock.objects.get(pk=pk)
	if request.method == 'POST':
		bulkstock.received_from = request.POST['received_from']
		bulkstock.remarks = request.POST['remarks']
		bulkstock.save()
		itemsinstock = Item.objects.filter(stock_associated=bulkstock)
		for item in itemsinstock:
			item.delete()
		savetostock(request,bulkstock)
		return redirect('/ecourts/editbulk/'+str(bulkstock.pk))
	context = {
		'bulk':bulkstock,
		'items':Item.objects.filter(stock_associated=bulkstock)
	}
	return render(request,'ecourts/received/editbulk.html',context)

def getstockajax(request,pk):
	items = Item.objects.filter(stock_associated=BulkStock.objects.get(pk=pk))
	itemsfree = items.filter(issued=False)
	itemstaken = items.filter(issued=True)
	return render(request,'ecourts/issue/ajaxissuedata.html',{'itemsfree':itemsfree,'itemstaken':itemstaken})

def viewallissued(request):
	issued = Issue.objects.all().order_by('-date')
	paginator = Paginator(issued, 12)
	page = request.GET.get('page')
	issued = paginator.get_page(page)
	return render(request,'ecourts/issue/viewallissued.html',{'issued':issued})

def detailissued(request,pk):
	if request.method == 'POST':
		issue = Issue.objects.get(pk=pk)
		issue.current_status = request.POST['current_status']
		issue.save()
		return redirect('/ecourts/detailissued/'+str(pk))
	issued = Issue.objects.get(pk=pk)
	return render(request,'ecourts/issue/detailissued.html',{'issued':issued})

ecourts/templates/ecourts/addstock.html
{% extends 'base.html' %}
{% block title %} Add stock to {{ category.category_name }} {% endblock %}
{% block content %}
<br><br>
<script>number_of_subcats=1</script>
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}	
	<input type="hidden" name="entered_by" value="{{ request.user.pk }}">
	<table class="table container table-bordered text-center">
		<tr>
			<td colspan="2" style="font-size: 1.5rem">Add Stock to {{ category.category_name }}</td>
		</tr>
		<tr>
			<td>Received from</td>
			<td><input type="text" name="received_from" class="form-control" autocomplete="off" required></td>
		</tr>
		<tr>
			<td>Ref no.</td>
			<td><input type="text" name="ref_no" class="form-control" autocomplete="off" required></td>
		</tr>
		<tr>
			<td>For Location</td>
			<td>
				<select name="location" class="form-control">
					<option value="">- - select - -</option>
					{% for l in location %}
					<option value="{{ l.pk }}">{{ l.location_name }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
		<tr>
			<td>Document</td>
			<td><input type="file" name="document" class="form-control" required></td>
		</tr>
		<tr>
			<td>Additional Document</td>
			<td><input type="file" name="add_document" class="form-control"></td>
		</tr>
		<tr>
			<td>Received Date</td>
			<td><input type="date" name="received_date" class="form-control" id="todaydate" required></td>
		</tr>
		<tr>
			<td>Remarks</td>
			<td><textarea name="remarks" cols="30" rows="5" class="form-control" required></textarea></td>
		</tr>
	</table>
	<hr class="container">
	<table class="table container table-bordered text-center" id="item-table">
		<tr>
			<td>
				<input type="text" name="description" class="form-control" placeholder="description" maxlength="500" required>
			</td>
			<td>
				<input type="text" name="sl_no" class="form-control" placeholder="Serial Number" maxlength="100" required>
			</td>
			<td>
				<input type="text" name="specification" class="form-control" placeholder="specification" maxlength="500">
			</td>
			<td>
				<input type="text" name="status" class="form-control" placeholder="status" maxlength="20">
			</td>
			<td>
				<input type="text" name="reason" class="form-control" placeholder="reason" maxlength="200">
			</td>
			<td><button type="button" class="btn btn-outline-primary btn-sm" onclick="addmorefunction()">Add</button></td>
		</tr>
	</table>
	<table class="table container table-borderless text-center">
		<tr>
			<td><input type="submit" class="btn btn-outline-success" value="Submit"></td>
		</tr>
	</table>
</form>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
	function addmorefunction(){
		number_of_subcats += 1;
		var row = '<tr id="subrow'+number_of_subcats+'"><td><input type="text" name="description" class="form-control" placeholder="description" maxlength="500" required><td><input type="text" name="sl_no" class="form-control" placeholder="Serial Number" maxlength="100" required></td><td>		<input type="text" name="specification" class="form-control" placeholder="specification" maxlength="500" required></td><td><input type="text" name="status" class="form-control" placeholder="status" maxlength="20" required></td><td><input type="text" name="reason" class="form-control" placeholder="reason" maxlength="200" required></td><td><button type="button" class="btn btn-outline-primary btn-sm" onclick="deletefield('+number_of_subcats+')">Delete</button>'
		$('#item-table').append(row);
	}

	function deletefield(x){
		var a = '#subrow'+x;
		$(a).remove();
		// number_of_subcats -= 1;
	}
	todaydate()
	function todaydate(){
		today = new Date()
		var year = today.getFullYear();
		var month = today.getMonth()+1;
		var day = today.getDate();
		var date = year;
		if (month<10) {
			date = date + '-0'+(month);
		}
		else{
			date = date + '-'+(month)
		}
		if (day<10) {
			date = date + '-0'+(day);
		}
		else{
			date = date + '-'+(day)
		}
		document.getElementById('todaydate').value = date;
	}
</script>
{% endblock %}

ecourts/templates/ecourts/index.html
{% extends 'base.html' %}
{% block title %}Stock Management System{% endblock %}
{% block content %}


<br>
<div class="container text-center">
	<h3>{{ categoryname }}</h3>
	<!-- <div class="p-3 m-3">
		<div class="card border-primary m-4" style="max-width: 100%">
			<a href="" class="text-decoration-none btn-outline-primary p-3">
				<h5 class="card-title">View Stock</h5>
			</a>
		</div>
	</div> -->
	<div style="border: 1px solid black; border-radius: 10px;" class="p-3 m-3">
		{% if user.is_authenticated %}
		<div class="card border-primary m-4" style="max-width: 100%">
			<a href="{% url 'ecourts:issue' %}" class="text-decoration-none btn-outline-primary p-3">
				<h5 class="card-title">Issue</h5>
			</a>
		</div>
		{% endif %}
		<div class="card border-primary m-4" style="max-width: 100%">
			<a href="{% url 'ecourts:viewallissued' %}" class="text-decoration-none btn-outline-primary p-3">
				<h5 class="card-title">View all Issued</h5>
			</a>
		</div>
	</div>
	<div style="border: 1px solid black; border-radius: 10px;" class="p-3 m-3">
		{% if user.is_authenticated %}
		<div class="card border-primary m-4" style="max-width: 100%">
			<a href="{% url 'ecourts:addstock' %}" class="text-decoration-none btn-outline-primary p-3">
				<h5 class="card-title">Add New Stock</h5>
			</a>
		</div>
		{% endif %}
		<div class="card border-primary m-4" style="max-width: 100%">
			<a href="{% url 'ecourts:viewreceived' %}" class="text-decoration-none btn-outline-primary p-3">
				<h5 class="card-title">View Received Stocks</h5>
			</a>
		</div>
	</div>
</div>
{% endblock %}