dashboard/urls.py
from django.urls import path
from .import views

app_name='dashboard'

urlpatterns = [
	path('',views.index, name='index'),
	path('category/<str:categoryname>',views.categoryview, name='categoryview'),
	path('issue/<str:categoryname>', views.issue, name='issue'),
	path('addstock/<str:categoryname>', views.addstock, name='addstock'),
	path('viewstock/<str:categoryname>',views.viewstock, name='viewstock'),
	path('getstockajax',views.getstockajax,name='getstock'),
	path('view-issued/<str:categoryname>',views.viewissued, name='viewissued'),
	path('view-purchased/<str:categoryname>', views.viewpurchased,name='viewpurchased'),
	path('usage/<str:categoryname>/<str:usagetype>', views.usage, name='usage'),
	path('viewdetailpurchase/<int:pk>',views.viewdetailpurchase,name='viewdetailpurchase'),
	path('viewdetailissued/<int:pk>',views.viewdetailissued,name='viewdetailissued'),
	path('usagereport/<str:categoryname>',views.usagereport,name='usagereport'),
	path('deleteissue/<int:pk>',views.deleteissue,name='deleteissue'),
	path('changeassignedlocation', views.changeassignedlocation, name='changeassignedlocation')
]

ecourts/urls.py
from django.urls import path
from .import views

app_name='ecourts'

urlpatterns = [
	path('',views.index, name='index'),
	path('addstock/',views.addstock,name='addstock'),
	path('viewreceived/',views.viewreceived, name='viewreceived'),
	path('receiveddetail/<int:pk>',views.receiveddetail,name='receiveddetail'),
	path('issue',views.issue, name='issue'),
	path('editbulk/<int:pk>',views.editbulk, name='editbulk'),
	path('getstockajax/<int:pk>',views.getstockajax, name='getstockajax'),
	path('viewallissued/',views.viewallissued,name='viewallissued'),
	path('detailissued/<int:pk>',views.detailissued,name='detailissued'),
]

stockmanagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dashboard.urls')),
    path('loginpage/',include('loginpage.urls')),
    path('accounts/',include('accounts.urls')),
    path('ecourts/',include('ecourts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from accounts.models import *


class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = '__all__'

dashboard/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from accounts.models import *
from .forms import *
from accounts.form import IssueForm
from django.core.paginator import Paginator
from .otherviewfunctions import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from datetime import datetime

@login_required(login_url='/loginpage')
def index(request):
	if request.user.is_authenticated:
		# if request.user.is_superuser:
		# 	categories=Category.objects.all()
		# else:
		# 	categories=Category.objects.filter(section=request.user.section)
		categories = Category.objects.filter(section=request.user.section,location=request.user.location)
	else:
		categories=Category.objects.all()
	return render(request,'dashboard/index.html', {'categories':categories})

def categoryview(request,categoryname):
	return render(request,'dashboard/viewcategory.html',{'categoryname':categoryname})

@login_required(login_url='/loginpage')
def issue(request,categoryname):
	if request.method == 'POST':
		form = IssueForm(compileissuedata(request),request.FILES)
		if form.is_valid():
			instance = form.save()
			messages.success(request, 'Items issued with id : '+str(instance.pk))
			return redirect('/category/'+categoryname)
		else:
			return HttpResponse(form.errors)
	return render(request,'dashboard/issue/issue.html',getcontext(categoryname))

@login_required(login_url='/loginpage')
def addstock(request,categoryname):
	if request.method == 'POST':
		form = EntryForm(compileaddstockdata(request),request.FILES)
		if form.is_valid():
			instance = form.save()
			sendstockaddmail(instance,request)
			messages.success(request, 'Stock added with id : '+str(instance.pk))
			return redirect('/category/'+categoryname)
		else:
			return HttpResponse(str(form.errors))
	return render(request,'dashboard/purchase/addstock.html',getcontext(categoryname))

def getstockajax(request):
	itempk = request.GET['itempk']
	item = Item.objects.get(pk=itempk)
	return HttpResponse(item.item_count)

def viewstock(request,categoryname):
	items = Item.objects.filter(category=Category.objects.get(category_name=categoryname))
	context = {'categoryname':categoryname,'items':items,}
	return render(request,'dashboard/viewstock.html',context)

def viewissued(request,categoryname):
	category = Category.objects.get(category_name=categoryname)
	issues = Issue.objects.filter(category=category).order_by('-date_of_issue')
	if request.GET.get('showreport'):
		issues = Issue.objects.filter(category=category).order_by('date_of_issue')
	searchfields = ['name','designation','item','section','issued_by','start_date','end_date']
	for field in searchfields:
		if request.GET.get(field):
			issues = searchissues(issues,request)
			break
	if request.GET.get('showreport'):
		templatename = 'dashboard/issue/report_issue.html'
		return render(request,templatename,
			givereportcontext(request,searchfields,issues,categoryname))
	context = getcontext(categoryname)
	paginator = Paginator(issues, 12)
	page = request.GET.get('page')
	issues = paginator.get_page(page)
	context['paginationdata'] = context['issued'] = issues
	return render(request,'dashboard/issue/viewissued.html',context)

def viewpurchased(request,categoryname):
	category = Category.objects.get(category_name=categoryname)
	entrys = Entry.objects.filter(category=category).order_by('-pk')
	if request.GET.get('showreport'):
		entrys = Entry.objects.filter(category=category)
	searchfields = ['item','entered_by','start_date','end_date','ref_no']
	for field in searchfields:
		if request.GET.get(field):
			entrys = searchentrys(entrys,request)
	if request.GET.get('showreport'):
		context = {'entrys':entrys,'categoryname':categoryname}
		return render(request,'dashboard/purchase/report_purchase.html',context)
	context = getcontext(categoryname)
	paginator = Paginator(entrys, 12)
	page = request.GET.get('page')
	entrys = paginator.get_page(page)
	context['entrys'] = context['paginationdata'] = entrys
	return render(request,'dashboard/purchase/viewpurchased.html',context)

def usage(request,categoryname,usagetype):
	if usagetype == 'itemandsection':
		items = Item.objects.filter(category=Category.objects.get(category_name=categoryname))
		itemsandusage = produceusagetypeboth(request,items)
		context = {
			'categoryname':categoryname,
			'itemsandusage':itemsandusage,
			'usagetype':usagetype,
			'items':items,
		}
		return render(request,'dashboard/usage/usageboth.html',context)
	
	if usagetype == 'section':
		usages = {}
		sections = Section.objects.all()
		categoryobj = Category.objects.get(category_name=categoryname)
		for section in sections:
			issues =  Issue.objects.filter(category=categoryobj,section=section)
			if request.GET.get('from'):
				issues = issues.filter(date_of_issue__gte=request.GET['from'],
				date_of_issue__lte=request.GET['to'])
			issues = issues.filter(section=section)
			sectionuse = 0
			for issue in issues:
				issueitem = issue.item
				subcatstring = issueitem.replace("\'","\"")
				subcatstring = json.loads(subcatstring)
				for key, value in subcatstring.items():
					sectionuse+=int(value)
			usages[section.section_name] = sectionuse

	if usagetype == 'item':
		usages = {}
		items = Item.objects.filter(category__category_name=categoryname)
		issues = Issue.objects.all()
		if request.GET.get('from'):
			issues = issues.filter(date_of_issue__gte=request.GET['from'],
				date_of_issue__lte=request.GET['to'])
		for item in items:		
			itemuse = 0
			for issue in issues:
				issueitem = issue.item
				subcatstring = issueitem.replace("\'","\"")
				subcatstring = json.loads(subcatstring)
				if str(item.pk) in subcatstring:
					itemuse += int(subcatstring[str(item.pk)])
			usages[item.item_name] = itemuse
	total = 0
	for key,value in usages.items():
		total += value
	context = {'usages':usages,'categoryname':categoryname,'usagetype':usagetype,'total':total}
	return render(request,'dashboard/usage/usage.html',context)

def viewdetailpurchase(request,pk):
	entry = Entry.objects.get(pk=pk)
	context = {'entry':entry,'category':entry.category}
	return render(request,'dashboard/purchase/viewdetailpurchased.html',context)

def viewdetailissued(request,pk):
	issue = Issue.objects.get(pk=pk)
	context = {'issue':issue,'category':issue.category}
	return render(request,'dashboard/issue/viewdetailissued.html',context)

def usagereport(request,categoryname):
	itemspk = request.GET.getlist('item')
	if len(itemspk)>0:
		items = Item.objects.filter(pk__in = itemspk)
	else:
		items = Item.objects.filter(category=Category.objects.get(category_name=categoryname))
	itemsandusage = produceusagetypeboth(request,items)
	context = {
		'itemsandusage':itemsandusage,
		'categoryname':categoryname,
	}
	if request.GET.get('from'):
		date_object = datetime.strptime(request.GET.get('from'), '%Y-%m-%d').date()
		fromdate = date_object.strftime('%d-%b-%Y')
		date_object = datetime.strptime(request.GET.get('to'), '%Y-%m-%d').date()
		todate = date_object.strftime('%d-%b-%Y')
		context['duration']='from '+str(fromdate)+' to '+str(todate)
	else:
		context['duration'] = 'all time'
	return render(request,'dashboard/usage/usagereportboth.html',context)

def deleteissue(request,pk):
	issue = Issue.objects.get(pk=pk)
	issueitem = issue.item
	subcatstring = issueitem.replace("\'","\"")
	subcatstring = json.loads(subcatstring)
	for key,value in subcatstring.items():
		# key ->item, value->quantity
		item = Item.objects.get(pk=key)
		count = item.item_count
		count+=int(value)
		item.item_count = count
		item.save()
	category = issue.category.category_name
	issue.delete()
	return redirect('/view-issued/'+category)

def changeassignedlocation(request):
	user = request.user
	location = Location.objects.get(pk=request.GET['location'])
	user.location = location
	user.save()
	return redirect(request.GET['currentpage'])

dashboard/templates/dashboard/index.html
{% extends 'base.html' %}
{% block title %}Stock Management System{% endblock %}
{% block content %}


<br>
<div class="container">
<div class="row">
	{% for category in categories %}
	<div class="col-sm-6 col-md-6 col-lg-4 col-xl-4 text-center">
		<a href="{% url 'dashboard:categoryview' category.category_name %}" class="text-decoration-none">
		<div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
			<div class="card-header"><h4>{{ category.category_name }}</h4></div>
			<div class="card-body">
				<h5 class="card-title">Issue/Add new Stock</h5>
			</div>
		</div>
		</a>
	</div>
	{% endfor %}
</div>
</div>
{% endblock %}

dashboard/templates/dashboard/viewcategory.html
{% extends 'base.html' %}
{% block title %} {{ categoryname }} {% endblock %}
{% block content %}
<br><br>
{% if messages %}
{% for message in messages %}
	<div class="alert alert-{{message.tags}} alert-dismissible fade show text-center container" role="alert">
		{{ message }}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
{% endfor %}
{% endif %}
<div class="container text-center">
	<h3>{{ categoryname }}</h3>
	<div class="p-3 m-3">
		<div class="card border-primary m-4" style="max-width: 100%">
			<a href="{% url 'dashboard:viewstock' categoryname %}" class="text-decoration-none btn-outline-primary p-3">
				<h5 class="card-title">View Stock</h5>
			</a>
		</div>
	</div>
	<div style="border: 1px solid black; border-radius: 10px;" class="p-3 m-3">
		{% if user.is_authenticated %}
		<div class="card border-primary m-4" style="max-width: 100%">
			<a href="{% url 'dashboard:issue' categoryname %}" class="text-decoration-none btn-outline-primary p-3">
				<h5 class="card-title">Issue</h5>
			</a>
		</div>
		{% endif %}
		<div class="card border-primary m-4" style="max-width: 100%">
			<a href="{% url 'dashboard:viewissued' categoryname %}" class="text-decoration-none btn-outline-primary p-3">
				<h5 class="card-title">View all Issued</h5>
			</a>
		</div>
	</div>
	<div style="border: 1px solid black; border-radius: 10px;" class="p-3 m-3">
		{% if user.is_authenticated %}
		<div class="card border-primary m-4" style="max-width: 100%">
			<a href="{% url 'dashboard:addstock' categoryname %}" class="text-decoration-none btn-outline-primary p-3">
				<h5 class="card-title">Add New Stock</h5>
			</a>
		</div>
		{% endif %}
		<div class="card border-primary m-4" style="max-width: 100%">
			<a href="{% url 'dashboard:viewpurchased' categoryname %}" class="text-decoration-none btn-outline-primary p-3">
				<h5 class="card-title">View Purchased Stocks</h5>
			</a>
		</div>
	</div>
</div>

{% endblock %}

dashboard/templates/dashboard/viewstock.html
{% extends 'base.html' %}
{% block title %} {{ categoryname}} stock {% endblock %}
{% block content %}
<br>
<table class="table container text-center table-bordered" style="border:0.5px solid black;">
	<tr>
		<td colspan="3"><p style="font-size: 2rem">{{ categoryname }} Stock Information</p></td>
	</tr>
	<tr>
		<th>Name</th>
		<th>Available</th>
		{% if user.is_authenticated %}
		<th></th>
		{% endif %}
	</tr>
{% for item in items %}
	<tr>
		<td>{{ item.item_name }}</td>
		<td>{{ item.item_count }}</td>
		{% if user.is_authenticated %}
		<td>
			<a href="{% url 'dashboard:issue' categoryname %}" class="btn btn-outline-success btn-sm">Issue</a>
			<a href="{% url 'dashboard:addstock' categoryname %}" class="btn btn-outline-primary btn-sm">Add stock</a>
		</td>
		{% endif %}
	</tr>
{% endfor %}
</table>
{% endblock %}