accounts/urls.py
from django.urls import path
from .import views

app_name='accounts'

urlpatterns = [
	path('',views.index, name='index'),
	path('item',views.item, name='item'),
	path('edititem/<int:pk>', views.edititem, name='edititem'),
	path('section',views.section, name='section'),
	path('email',views.email, name='email'),
	path('locations',views.locations, name='locations'),
]

dashboard/urls.py
from django.urls import path
from .import views

app_name='dashboard'

urlpatterns = [
	path('',views.index, name='index'),
	path('category/<str:categoryname>',views.categoryview, name='categoryview'),
	path('issue/<str:categoryname>', views.issue, name='issue'),
	path('addstock/<str:categoryname>', views.addstock, name='addstock'),
	path('viewstock/<str:categoryname>',views.viewstock, name='viewstock'),
	path('getstockajax',views.getstockajax,name='getstock'),
	path('view-issued/<str:categoryname>',views.viewissued, name='viewissued'),
	path('view-purchased/<str:categoryname>', views.viewpurchased,name='viewpurchased'),
	path('usage/<str:categoryname>/<str:usagetype>', views.usage, name='usage'),
	path('viewdetailpurchase/<int:pk>',views.viewdetailpurchase,name='viewdetailpurchase'),
	path('viewdetailissued/<int:pk>',views.viewdetailissued,name='viewdetailissued'),
	path('usagereport/<str:categoryname>',views.usagereport,name='usagereport'),
	path('deleteissue/<int:pk>',views.deleteissue,name='deleteissue'),
	path('changeassignedlocation', views.changeassignedlocation, name='changeassignedlocation')
]

ecourts/urls.py
from django.urls import path
from .import views

app_name='ecourts'

urlpatterns = [
	path('',views.index, name='index'),
	path('addstock/',views.addstock,name='addstock'),
	path('viewreceived/',views.viewreceived, name='viewreceived'),
	path('receiveddetail/<int:pk>',views.receiveddetail,name='receiveddetail'),
	path('issue',views.issue, name='issue'),
	path('editbulk/<int:pk>',views.editbulk, name='editbulk'),
	path('getstockajax/<int:pk>',views.getstockajax, name='getstockajax'),
	path('viewallissued/',views.viewallissued,name='viewallissued'),
	path('detailissued/<int:pk>',views.detailissued,name='detailissued'),
]

loginpage/urls.py
from django.urls import path
from .import views

app_name='loginpage'

urlpatterns = [
	# path('',views.index, name='index'),
	path('',views.loginuser,name='loginuser'),
	path('logout',views.logoutuser,name='logoutuser'),
	path('register',views.register,name='register'),
	path('changepassword',views.changepassword, name='changepassword'),
]

stockmanagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dashboard.urls')),
    path('loginpage/',include('loginpage.urls')),
    path('accounts/',include('accounts.urls')),
    path('ecourts/',include('ecourts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from accounts.models import *


class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = '__all__'

dashboard/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from accounts.models import *
from .forms import *
from accounts.form import IssueForm
from django.core.paginator import Paginator
from .otherviewfunctions import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from datetime import datetime

@login_required(login_url='/loginpage')
def index(request):
	if request.user.is_authenticated:
		# if request.user.is_superuser:
		# 	categories=Category.objects.all()
		# else:
		# 	categories=Category.objects.filter(section=request.user.section)
		categories = Category.objects.filter(section=request.user.section,location=request.user.location)
	else:
		categories=Category.objects.all()
	return render(request,'dashboard/index.html', {'categories':categories})

def categoryview(request,categoryname):
	return render(request,'dashboard/viewcategory.html',{'categoryname':categoryname})

@login_required(login_url='/loginpage')
def issue(request,categoryname):
	if request.method == 'POST':
		form = IssueForm(compileissuedata(request),request.FILES)
		if form.is_valid():
			instance = form.save()
			messages.success(request, 'Items issued with id : '+str(instance.pk))
			return redirect('/category/'+categoryname)
		else:
			return HttpResponse(form.errors)
	return render(request,'dashboard/issue/issue.html',getcontext(categoryname))

@login_required(login_url='/loginpage')
def addstock(request,categoryname):
	if request.method == 'POST':
		form = EntryForm(compileaddstockdata(request),request.FILES)
		if form.is_valid():
			instance = form.save()
			sendstockaddmail(instance,request)
			messages.success(request, 'Stock added with id : '+str(instance.pk))
			return redirect('/category/'+categoryname)
		else:
			return HttpResponse(str(form.errors))
	return render(request,'dashboard/purchase/addstock.html',getcontext(categoryname))

def getstockajax(request):
	itempk = request.GET['itempk']
	item = Item.objects.get(pk=itempk)
	return HttpResponse(item.item_count)

def viewstock(request,categoryname):
	items = Item.objects.filter(category=Category.objects.get(category_name=categoryname))
	context = {'categoryname':categoryname,'items':items,}
	return render(request,'dashboard/viewstock.html',context)

def viewissued(request,categoryname):
	category = Category.objects.get(category_name=categoryname)
	issues = Issue.objects.filter(category=category).order_by('-date_of_issue')
	if request.GET.get('showreport'):
		issues = Issue.objects.filter(category=category).order_by('date_of_issue')
	searchfields = ['name','designation','item','section','issued_by','start_date','end_date']
	for field in searchfields:
		if request.GET.get(field):
			issues = searchissues(issues,request)
			break
	if request.GET.get('showreport'):
		templatename = 'dashboard/issue/report_issue.html'
		return render(request,templatename,
			givereportcontext(request,searchfields,issues,categoryname))
	context = getcontext(categoryname)
	paginator = Paginator(issues, 12)
	page = request.GET.get('page')
	issues = paginator.get_page(page)
	context['paginationdata'] = context['issued'] = issues
	return render(request,'dashboard/issue/viewissued.html',context)

def viewpurchased(request,categoryname):
	category = Category.objects.get(category_name=categoryname)
	entrys = Entry.objects.filter(category=category).order_by('-pk')
	if request.GET.get('showreport'):
		entrys = Entry.objects.filter(category=category)
	searchfields = ['item','entered_by','start_date','end_date','ref_no']
	for field in searchfields:
		if request.GET.get(field):
			entrys = searchentrys(entrys,request)
	if request.GET.get('showreport'):
		context = {'entrys':entrys,'categoryname':categoryname}
		return render(request,'dashboard/purchase/report_purchase.html',context)
	context = getcontext(categoryname)
	paginator = Paginator(entrys, 12)
	page = request.GET.get('page')
	entrys = paginator.get_page(page)
	context['entrys'] = context['paginationdata'] = entrys
	return render(request,'dashboard/purchase/viewpurchased.html',context)

def usage(request,categoryname,usagetype):
	if usagetype == 'itemandsection':
		items = Item.objects.filter(category=Category.objects.get(category_name=categoryname))
		itemsandusage = produceusagetypeboth(request,items)
		context = {
			'categoryname':categoryname,
			'itemsandusage':itemsandusage,
			'usagetype':usagetype,
			'items':items,
		}
		return render(request,'dashboard/usage/usageboth.html',context)
	
	if usagetype == 'section':
		usages = {}
		sections = Section.objects.all()
		categoryobj = Category.objects.get(category_name=categoryname)
		for section in sections:
			issues =  Issue.objects.filter(category=categoryobj,section=section)
			if request.GET.get('from'):
				issues = issues.filter(date_of_issue__gte=request.GET['from'],
				date_of_issue__lte=request.GET['to'])
			issues = issues.filter(section=section)
			sectionuse = 0
			for issue in issues:
				issueitem = issue.item
				subcatstring = issueitem.replace("\'","\"")
				subcatstring = json.loads(subcatstring)
				for key, value in subcatstring.items():
					sectionuse+=int(value)
			usages[section.section_name] = sectionuse

	if usagetype == 'item':
		usages = {}
		items = Item.objects.filter(category__category_name=categoryname)
		issues = Issue.objects.all()
		if request.GET.get('from'):
			issues = issues.filter(date_of_issue__gte=request.GET['from'],
				date_of_issue__lte=request.GET['to'])
		for item in items:		
			itemuse = 0
			for issue in issues:
				issueitem = issue.item
				subcatstring = issueitem.replace("\'","\"")
				subcatstring = json.loads(subcatstring)
				if str(item.pk) in subcatstring:
					itemuse += int(subcatstring[str(item.pk)])
			usages[item.item_name] = itemuse
	total = 0
	for key,value in usages.items():
		total += value
	context = {'usages':usages,'categoryname':categoryname,'usagetype':usagetype,'total':total}
	return render(request,'dashboard/usage/usage.html',context)

def viewdetailpurchase(request,pk):
	entry = Entry.objects.get(pk=pk)
	context = {'entry':entry,'category':entry.category}
	return render(request,'dashboard/purchase/viewdetailpurchased.html',context)

def viewdetailissued(request,pk):
	issue = Issue.objects.get(pk=pk)
	context = {'issue':issue,'category':issue.category}
	return render(request,'dashboard/issue/viewdetailissued.html',context)

def usagereport(request,categoryname):
	itemspk = request.GET.getlist('item')
	if len(itemspk)>0:
		items = Item.objects.filter(pk__in = itemspk)
	else:
		items = Item.objects.filter(category=Category.objects.get(category_name=categoryname))
	itemsandusage = produceusagetypeboth(request,items)
	context = {
		'itemsandusage':itemsandusage,
		'categoryname':categoryname,
	}
	if request.GET.get('from'):
		date_object = datetime.strptime(request.GET.get('from'), '%Y-%m-%d').date()
		fromdate = date_object.strftime('%d-%b-%Y')
		date_object = datetime.strptime(request.GET.get('to'), '%Y-%m-%d').date()
		todate = date_object.strftime('%d-%b-%Y')
		context['duration']='from '+str(fromdate)+' to '+str(todate)
	else:
		context['duration'] = 'all time'
	return render(request,'dashboard/usage/usagereportboth.html',context)

def deleteissue(request,pk):
	issue = Issue.objects.get(pk=pk)
	issueitem = issue.item
	subcatstring = issueitem.replace("\'","\"")
	subcatstring = json.loads(subcatstring)
	for key,value in subcatstring.items():
		# key ->item, value->quantity
		item = Item.objects.get(pk=key)
		count = item.item_count
		count+=int(value)
		item.item_count = count
		item.save()
	category = issue.category.category_name
	issue.delete()
	return redirect('/view-issued/'+category)

def changeassignedlocation(request):
	user = request.user
	location = Location.objects.get(pk=request.GET['location'])
	user.location = location
	user.save()
	return redirect(request.GET['currentpage'])

dashboard/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title%}{% endblock %}</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'bootstrap-5.0.2/css/bootstrap.min.css' %}">
	<script src="{% static 'bootstrap-5.0.2/js/bootstrap.bundle.min.js' %}"></script>
</head>
{% load customtag %}
<body>
	<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
		<div class="container-fluid">
			<a class="navbar-brand" href="/">Home</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			Office :&nbsp
			<form action="{% url 'dashboard:changeassignedlocation' %}" class="form-inline">
				<input type="hidden" name="currentpage" value="{{ request.path }}">
			  {{ request.user.location|putlocationoption|safe }}
			</form>
			<div class="collapse navbar-collapse" id="navbarNavDropdown">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					{% if user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="{% url 'accounts:index' %}">Accounts</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="{% url 'ecourts:index' %}">Ecourt project</a>
					</li>
					{% endif %}
				</ul>
				welcome {{ request.user }} &nbsp
				{% if user.is_authenticated %}
				<a href="{% url 'loginpage:logoutuser' %}?next={{ request.path }}" class="btn btn-outline-danger">Logout</a>
				{% else %}
				<a href="{% url 'loginpage:loginuser' %}?next={{ request.path }}" class="btn btn-outline-danger">Login</a>
				{% endif %}
			</div>
		</div>
	</nav>

	{% block content %}
	{% endblock %}
</body>
</html>

dashboard/templates/pagination.html
{% load customtag %}
<nav aria-label="Page navigation example">
	<ul class="pagination justify-content-center">
		{% if paginationdata.has_previous %}
		<li class="page-item"><a class="page-link" href="?{% url_replace request 'page' paginationdata.previous_page_number %}">Previous</a></li>
		{% else %}
		<li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
		{% endif %}
		{% if paginationdata.number|add:'-4' > 1 %}
		<li class="text-dark page-item">
			<a href="?page=1" class="page-link">1</a>
		</li>
		<li>
			<a href="?{% url_replace request 'page' paginationdata.number|add:'-5' %}" class="page-link">&hellip;</a>
		</li>
		{% endif %}
		{% for i in paginationdata.paginator.page_range %}
		{% if paginationdata.number == i %}
		<li class="page-item active">
			<a href="?{% url_replace request 'page' i %}" class="page-link">{{i}}</a>
		</li>
		{% elif i > paginationdata.number|add:'-5' and i < paginationdata.number|add:'5' %}
		<li class="page-item {% if i == paginationdata.number %} active {% endif %}">
			<a href="?{% url_replace request 'page' i %}" class="page-link">{{i}}</a>
		</li>
		{% endif %}
		{% endfor %}
		{% if paginationdata.paginator.num_pages > paginationdata.number|add:'4' %}
		<li class="page-item">
			<a href="?{% url_replace request 'page' paginationdata.number|add:'5' %}" class="page-link">&hellip;</a>
		</li>
		{% if book.number != paginationdata.paginator.num_pages %}
		<li class="text-dark page-item">
			<a href="?{% url_replace request 'page' paginationdata.paginator.num_pages %}" class="page-link">{{ paginationdata.paginator.num_pages }}</a>
		</li>
		{% endif %}
		{% endif %}
		{% if paginationdata.has_next %}
		<li class="page-item"><a class="page-link" href="?{% url_replace request 'page' paginationdata.next_page_number %}">Next</a></li>
		{% else %}
		<li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
		{% endif %}
	</ul>
</nav>